language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-software-properties

  # SFML
  - sudo apt-add-repository -y ppa:sonkun/sfml-development

  # GCC 4.8
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get update
  - sudo apt-get install -y libsfml-dev libdumb1-dev gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

