language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-software-properties
  - sudo apt-add-repository -y ppa:sonkun/sfml-stable

install:
  - sudo apt-get update
  - sudo apt-get install -y sfml libdumb1-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

